# Generated by Django 3.0.7 on 2020-06-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='number1',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='number2',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='operator',
            field=models.TextField(default='+'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='result',
            field=models.FloatField(default=3),
        ),
    ]
