# Generated by Django 3.0.7 on 2020-06-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_calculation_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='result',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
