# Generated by Django 3.0.7 on 2020-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20200630_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='operator',
        ),
        migrations.AddField(
            model_name='calculation',
            name='operator_text',
            field=models.CharField(default='+', max_length=2),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='number1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='number2',
            field=models.FloatField(default=0),
        ),
    ]
