# Generated by Django 3.0.7 on 2020-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20200630_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='geeks_field',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], default='1', max_length=20),
        ),
    ]
