# Generated by Django 3.0.7 on 2020-06-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_calculation_geeks_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='result',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
