# Generated by Django 3.0.7 on 2020-06-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_auto_20200630_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='geeks_field',
        ),
    ]
