# Generated by Django 3.0.7 on 2020-07-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_remove_calculation_geeks_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='number2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
