# Generated by Django 3.0.7 on 2020-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_auto_20200702_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='number2',
            field=models.CharField(blank=True, default='', max_length=100000000, null=True),
        ),
    ]
